<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/dojo/1.3/dijit/themes/nihilo/nihilo.css" />
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
djConfig={
          parseOnLoad: true,
          baseUrl: "./",
          modulePaths: { custom: "/js/dojo/custom" }
        };
</script>
<script type="text/javascript">google.load("dojo", "1.3", {uncompressed:true});</script>
<link type="text/css" rel="stylesheet" href="/css/form.css"/>
<!--LINK rel="stylesheet" type="text/css" href="/css/jot-old.css"-->
<!--LINK rel="stylesheet" type="text/css" href="/css/list.css"-->
<style type="text/css">
#goog-ws-left .goog-ws-outside, #goog-ws-left .goog-ws-subfooter,
#goog-ws-left-nohead .goog-ws-outside, #goog-ws-left-nohead .goog-ws-subfooter {
margin: 0 0 0 150px;
}
#goog-ws-right .goog-ws-outside, #goog-ws-right .goog-ws-subfooter,
#goog-ws-right-nohead .goog-ws-outside, #goog-ws-right-nohead .goog-ws-subfooter {
margin: 0 150px 0 0;
}
.goog-ws-outer {
margin-left: auto !important;
margin-right: auto !important;
width: 100%;
}
.goog-ws-sidebar {
width: 145px;
}</style>
