<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/dojo/1.3/dijit/themes/nihilo/nihilo.css" />
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
djConfig={
          parseOnLoad: true,
          baseUrl: "./",
          modulePaths: { custom: "/js/dojo/custom" }
        };
</script>
<script type="text/javascript">google.load("dojo", "1.3", {uncompressed:false});</script>
<!--link type="text/css" rel="stylesheet" href="/css/form.css"/-->
