application: test-pappa-mi-hr
version: 1
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "1d"

derived_file_type:
- python_precompiled

builtins:
- remote_api: on 
- appstats: on
- deferred: on

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: setuptools
  version: latest
- name: markupsafe
  version: latest
  
inbound_services:
- mail

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.bak)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
 
handlers:

- url: /_ah/mail/.+ 
  script: py.handle_incoming_email.app 
  login: admin
  
- url: /admin/dblog
  script: py.dblog.app
  login: admin
  
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /(.*\.(gif|png|jpg|txt|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|txt|html))

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /admin/stats/*
  script: py.stats.app
  login: admin  

- url: /admin/stats/.*
  script: py.stats.app
  login: admin  
  
- url: /admin/.*
  script: py.admin.app
  login: admin

- url: /admin/*
  script: py.admin.app
  login: admin
  
- url: /public/.*
  script: py.public.app

- url: /isp/.*
  script: py.ispezioni.app   
  
- url: /stats/.*
  script: py.stats.app

- url: /stats/*
  script: py.stats.app

- url: /feed/.*
  script: py.feed.app

- url: /feed/*
  script: py.feed.app

- url: /widget/.*
  script: py.widget.app
  
- url: /widget/*
  script: py.widget.app
 
#- url: /_ah/login_required
#  script: py.login.app

#- url: /_ah/login_required
#  script: py.login.app

#- url: /login
#  script: py.login.app
#  login: required

- url: /fb
  script: py.fb.app

- url: /fb/*
  script: py.fb.app

- url: /fb/.*
  script: py.fb.app

- url: /comments/*
  script: py.comments.app

- url: /comments/.*
  script: py.comments.app

- url: /profilo/*
  script: py.profilo.app

- url: /profilo/.*
  script: py.profilo.app

- url: /signup
  script: py.signup.app

- url: /blob/*
  script: py.blob.app

- url: /blob/.*
  script: py.blob.app

- url: /commissioni/.*
  script: py.commissioni.app

- url: /commissioni/*
  script: py.commissioni.app
  
- url: /contatti/.*
  script: py.commissioni.app

- url: /contatti/*
  script: py.commissioni.app
  
- url: /login
  script: py.eauth.main.application

- url: /logout
  script: py.eauth.main.application

- url: /home
  script: py.eauth.main.application
  
- url: /protected
  script: py.eauth.main.application

- url: /menu/.*
  script: py.menu.app

- url: /menu/*
  script: py.menu.app
  
- url: /menuslide/.*
  script: py.menu.app

- url: /menuslide/*
  script: py.menu.app
  
- url: .*
  script: py.main.app


  
  