application: test-pappa-mi-hr
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

derived_file_type:
- python_precompiled

builtins:
- remote_api: on 
- appstats: off
- deferred: on

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: setuptools
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: 2.3
  
inbound_services:
- mail
- channel_presence

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.bak)|
 (.*/RCS/.*)|
 (\..*)| 
 )$

handlers:

- url: /_ah/mail/node-.*
  script: handle_node_email.app
  login: admin

- url: /_ah/mail/.+ 
  script: py.handle_incoming_email.app 
  login: admin
  
- url: /admin/dblog
  script: py.dblog.app
  login: admin
  
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /(.*\.(gif|png|jpg|txt|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|txt|html))

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /_ah/login_required
  script: py.login.app
  
- url: /admin/stats.*
  script: py.stats.app
  login: admin
  
- url: /admin.*
  script: py.admin.app
  login: admin
  
- url: /public/.*
  script: py.public.app

- url: /isp/.*
  script: py.ispezioni.app   
  
- url: /stats.*
  script: py.stats.app

- url: /feed.*
  script: py.feed.app

- url: /widget.*
  script: py.widget.app
   
- url: /fb.*
  script: py.fb.app

- url: /comments.*
  script: py.comments.app

- url: /profilo.*
  script: py.profilo.app

- url: /signup
  script: py.signup.app

- url: /signup2
  script: py.signup.app
  
- url: /blob/*
  script: py.blob.app

- url: /blob/.*
  script: py.blob.app

- url: /commissioni.*
  script: py.commissioni.app
  
- url: /contatti.*
  script: py.commissioni.app

- url: /eauth.*
  script: py.login.app
  
- url: /menu.*
  script: py.menu.app
  
- url: /menuslide.*
  script: py.menu.app

- url: /search
  script: py.search.app

- url: /event.*
  script: py.event.app
  login: admin

- url: /ntfctn.*
  script: py.event.app

- url: /node.*
  script: py.node.app

- url: /post.*
  script: py.post.app

- url: /search
  script: py.search.app

- url: /stream.*
  script: py.stream.app

- url: /api/.*
  script: py.api.app

- url: /mobile.*
  script: py.mobile.app

- url: /_ah/channel.*
  script: py.channel.app
  
- url: .*
  script: py.main.app


  
  