application: pappa-mi
version: 1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.bak)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
 
handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /commissario/.*
  script: py/commissario.py
  login: required

- url: /commissario/*
  script: py/commissario.py
  login: required

- url: /admin/.*
  script: py/admin.py
  login: admin

- url: /admin/*
  script: py/admin.py
  login: admin

- url: /stats/.*
  script: py/stats.py
  login: required

- url: /stats/*
  script: py/stats.py
  login: required
  
- url: .*
  script: py/main.py
