<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
{%if test%}
var pageTracker = _gat._getTracker("UA-8652590-3");
{%else%}
var pageTracker = _gat._getTracker("UA-8652590-2");
{%endif%}
pageTracker._trackPageview();
} catch(err) {}</script>